export const FETCH_BUCKETS = 'FETCH_BUCKETS';
export const FETCH_BUCKETS_SUCCEESS = 'FETCH_BUCKETS_SUCCEESS';
export const FETCH_BUCKETS_FAILURE = 'FETCH_BUCKETS_FAILURE';
export const UPDATE_BUCKETS = 'UPDATE_BUCKETS';
export const UPDATE_BUCKETS_SUCCEESS = 'UPDATE_BUCKETS_SUCCEESS';
export const UPDATE_BUCKETS_FAILURE = 'UPDATE_BUCKETS_FAILURE';
export const REMOVE_BUCKETS = 'REMOVE_BUCKETS';
export const REMOVE_BUCKETS_SUCCEESS = 'REMOVE_BUCKETS_SUCCEESS';
export const REMOVE_BUCKETS_FAILURE = 'REMOVE_BUCKETS_FAILURE';
export const CREATE_BUCKETS = 'CREATE_BUCKETS';
export const CREATE_BUCKETS_SUCCEESS = 'CREATE_BUCKETS_SUCCEESS';
export const CREATE_BUCKETS_FAILURE = 'CREATE_BUCKETS_FAILURE';


export const FETCH_TODO_LISTS = 'FETCH_TODO_LISTS';
export const FETCH_TODO_LISTS_SUCCESS = 'FETCH_TODO_LISTS_SUCCESS';
export const FETCH_TODO_LISTS_FAILURE = 'FETCH_TODO_LISTS_FAILURE';
export const UPDATE_TODO_LISTS = 'UPDATE_TODO_LISTS';
export const UPDATE_TODO_LISTS_SUCCESS = 'UPDATE_TODO_LISTS_SUCCESS';
export const UPDATE_TODO_LISTS_FAILURE = 'UPDATE_TODO_LISTS_FAILURE';
export const CREATE_TODO_LISTS = 'CREATE_TODO_LISTS';
export const CREATE_TODO_LISTS_SUCCESS = 'CREATE_TODO_LISTS_SUCCESS';
export const CREATE_TODO_LISTS_FAILURE = 'CREATE_TODO_LISTS_FAILURE';
export const REMOVE_TODO_LISTS = 'REMOVE_TODO_LISTS';
export const REMOVE_TODO_LISTS_SUCCESS = 'REMOVE_TODO_LISTS_SUCCESS';
export const REMOVE_TODO_LISTS_FAILURE = 'REMOVE_TODO_LISTS_FAILURE';